// <auto-generated />
using System;
using IT64_2019_URIS_ExpertCommission.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT64_2019_URIS_ExpertCommission.Migrations
{
    [DbContext(typeof(ExpertCommissionAPIDbContext))]
    [Migration("20230213073957_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IT64_2019_URIS_ExpertCommission.Entities.ExpertCommission", b =>
                {
                    b.Property<Guid>("ExpertCommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpertCommissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("PresidentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpertCommissionId");

                    b.ToTable("ExpertCommissions");
                });

            modelBuilder.Entity("IT64_2019_URIS_ExpertCommission.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExpertCommissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.HasIndex("ExpertCommissionId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("IT64_2019_URIS_ExpertCommission.Entities.Member", b =>
                {
                    b.HasOne("IT64_2019_URIS_ExpertCommission.Entities.ExpertCommission", "ExpertCommission")
                        .WithMany("Members")
                        .HasForeignKey("ExpertCommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertCommission");
                });

            modelBuilder.Entity("IT64_2019_URIS_ExpertCommission.Entities.ExpertCommission", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
