// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Township.Entities;

#nullable disable

namespace Township.Migrations
{
    [DbContext(typeof(TownshipContext))]
    [Migration("20230215232357_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Township.Models.TownshipDto", b =>
                {
                    b.Property<Guid>("IdTownship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameOfTownship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTownship");

                    b.ToTable("Township");

                    b.HasData(
                        new
                        {
                            IdTownship = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            NameOfTownship = "Old town"
                        },
                        new
                        {
                            IdTownship = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            NameOfTownship = "New town"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
