// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URIS_OGLAS_IT72.Data;

#nullable disable

namespace URIS_OGLAS_IT72.Migrations
{
    [DbContext(typeof(AdverAPIDbContext))]
    partial class AdverAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("URIS_OGLAS_IT72.Models.Domain.Advertisment", b =>
                {
                    b.Property<Guid>("AdvertismentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DecisionOfAdvertismentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipGaranta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvertismentId");

                    b.HasIndex("DecisionOfAdvertismentId");

                    b.ToTable("Advertisments");
                });

            modelBuilder.Entity("URIS_OGLAS_IT72.Models.Domain.DecisionOfAdvertisment", b =>
                {
                    b.Property<Guid>("DecisionOfAdvertismentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivOdluke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeDonosenja")
                        .HasColumnType("datetime2");

                    b.HasKey("DecisionOfAdvertismentId");

                    b.ToTable("DecisionOfAdvertisments");
                });

            modelBuilder.Entity("URIS_OGLAS_IT72.Models.Domain.Advertisment", b =>
                {
                    b.HasOne("URIS_OGLAS_IT72.Models.Domain.DecisionOfAdvertisment", "DecisionOfAdvertisments")
                        .WithMany("Advertisments")
                        .HasForeignKey("DecisionOfAdvertismentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionOfAdvertisments");
                });

            modelBuilder.Entity("URIS_OGLAS_IT72.Models.Domain.DecisionOfAdvertisment", b =>
                {
                    b.Navigation("Advertisments");
                });
#pragma warning restore 612, 618
        }
    }
}
