// <auto-generated />
using System;
using Land.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Land.Migrations.List
{
    [DbContext(typeof(ListContext))]
    [Migration("20230216155039_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Land.Models.ListDto", b =>
                {
                    b.Property<Guid>("IdList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LabelLand")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SumSurface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdList");

                    b.ToTable("List");

                    b.HasData(
                        new
                        {
                            IdList = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            LabelLand = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            SumSurface = "500m2"
                        },
                        new
                        {
                            IdList = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            LabelLand = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            SumSurface = "1500m2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
