// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URIS_Licitacion_IT67_2019.Data;

#nullable disable

namespace URIS_Licitacion_IT67_2019.Migrations
{
    [DbContext(typeof(LicitationDbContext))]
    partial class LicitationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("URIS_Licitacion_IT67_2019.Entities.Licitation", b =>
                {
                    b.Property<Guid>("LicitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfAnnouncment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineForSubmission")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ListOfIndividuals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListOfLegalEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfLic")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("secondRound")
                        .HasColumnType("bit");

                    b.HasKey("LicitationId");

                    b.ToTable("Licitacions");
                });
#pragma warning restore 612, 618
        }
    }
}
