// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URIS_Stages_it24.Data;

#nullable disable

namespace URIS_Stages_it24.Migrations
{
    [DbContext(typeof(StagesApiDbContext))]
    [Migration("20230213212618_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("URIS_Stages_it24.Models.Entities.Stage", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StageDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.HasKey("StageId");

                    b.ToTable("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
