// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URIS_DEOPARCELE_IT72.Data;

#nullable disable

namespace URIS_DEOPARCELE_IT72.Migrations
{
    [DbContext(typeof(PartParcelAPIDbContext))]
    partial class PartParcelAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("URIS_DEOPARCELE_IT72.Models.Domain.PartOfParcel", b =>
                {
                    b.Property<Guid>("PartOfParcelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KvalitetZemljiste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PovrsinaDelaParcele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartOfParcelID");

                    b.ToTable("PartOfParcels");
                });
#pragma warning restore 612, 618
        }
    }
}
