// <auto-generated />
using System;
using Complaint.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Complaint.Migrations.Decision
{
    [DbContext(typeof(DecisionContext))]
    partial class DecisionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Complaint.Models.DecisionDto", b =>
                {
                    b.Property<Guid>("IdDecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MinistryOpinion")
                        .HasColumnType("bit");

                    b.HasKey("IdDecision");

                    b.ToTable("Decision");

                    b.HasData(
                        new
                        {
                            IdDecision = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            DecisionDate = new DateTime(2017, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinistryOpinion = true
                        },
                        new
                        {
                            IdDecision = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            DecisionDate = new DateTime(2017, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinistryOpinion = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
