// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URIS_ProtectedZone_IT67_2019.Data;

#nullable disable

namespace URIS_ProtectedZone_IT67_2019.Migrations
{
    [DbContext(typeof(ProtectedZoneDbContext))]
    [Migration("20230214200802_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("URIS_ProtectedZone_IT67_2019.Entities.DocumentProtectedZone", b =>
                {
                    b.Property<Guid>("DocumentProtectedZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfSubmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermitedWorks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProtectedZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReferenceNumber")
                        .HasColumnType("int");

                    b.HasKey("DocumentProtectedZoneId");

                    b.HasIndex("ProtectedZoneId");

                    b.ToTable("DocumentProtectedZones");
                });

            modelBuilder.Entity("URIS_ProtectedZone_IT67_2019.Entities.ProtectedZone", b =>
                {
                    b.Property<Guid>("ProtectedZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfZone")
                        .HasColumnType("int");

                    b.Property<string>("PermittedWorks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProtectedZoneId");

                    b.ToTable("ProtectedZones");
                });

            modelBuilder.Entity("URIS_ProtectedZone_IT67_2019.Entities.DocumentProtectedZone", b =>
                {
                    b.HasOne("URIS_ProtectedZone_IT67_2019.Entities.ProtectedZone", "ProtectedZone")
                        .WithMany("DocumentProtectedZones")
                        .HasForeignKey("ProtectedZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtectedZone");
                });

            modelBuilder.Entity("URIS_ProtectedZone_IT67_2019.Entities.ProtectedZone", b =>
                {
                    b.Navigation("DocumentProtectedZones");
                });
#pragma warning restore 612, 618
        }
    }
}
